name: shiny_geo
channels:
  - conda-forge
  - defaults
dependencies:
  - fiona=1.9.5
  - folium=0.14.0
  - gdal=3.7.2
  - geocube=0.4.2
  - geopandas=0.14.0
  - jupyter=1.0.0
  - jupyterlab=4.0.7
  - mapclassify=2.6.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.6
  - netcdf4=1.6.5
  - notebook=7.0.6
  - numpy=1.24.4
  - pandas=1.5.3
  - pandoc=3.1.3
  - pip=23.3
  - plotly=5.18.0
  - proj=9.3.0
  - pyproj=3.6.1
  - python=3.10.13
  - rasterio=1.3.9
  - rioxarray=0.15.0
  - seaborn=0.13.0
  - shapely=2.0.2
  - shiny=0.6.0
  - widgetsnbextension=4.0.9
  - xarray=2023.2.0
  - pip:
      - shinywidgets==0.2.1
